apiVersion: apps/v1
kind: Deployment
metadata:
  name: non-privilidged-bblog
  namespace: vmservice
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: non-privilidged-bblog
  template:
    metadata:
      labels:
        app: non-privilidged-bblog
    spec:
      containers:
        - image: harbor.home.ads:443/library/upbblog:v2
          name: non-privilidged-bblog
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 1111
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
