apiVersion: v1
kind: Service
metadata:
  name: non-privilidged-bblog-lb
  namespace: vmservice
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: non-privilidged-bblog
  type: LoadBalancer
